<a href="https://colab.research.google.com/github/Mannshah2732/datascience_assignment/blob/main/Numpy_Assignment_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practical Questions**

In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

array1 = np.random.randint(1, 101, size = (3, 3))

print("Original Array : \n", array1)

transpose_array = array1.T

print("Transpose Array : \n", transpose_array)

Original Array : 
 [[11 72  5]
 [93 78 71]
 [41 87 50]]
Transpose Array : 
 [[11 93 41]
 [72 78 87]
 [ 5 71 50]]


In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

import numpy as np

array1 = np.arange(10)
print("Original 1D Array : \n", array1)

reshape_2x5 = array1.reshape(2, 5)
print("\n Reshaped 2x5 Array : \n", reshape_2x5)

reshape_5x2 = array1.reshape(5, 2)
print("\n Reshaped 5x2 Array : \n", reshape_5x2)

Original 1D Array : 
 [0 1 2 3 4 5 6 7 8 9]

 Reshaped 2x5 Array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

 Reshaped 5x2 Array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

array1 = np.random.rand(4, 4)
print("Original 4x4 Array : \n", array1)

array_border = np.pad(array1, pad_width = 1, mode = 'constant', constant_values = 0)

print("\n 6x6 Array with border 0 : \n", array_border)

Original 4x4 Array : 
 [[0.53435733 0.90728663 0.84298865 0.17068102]
 [0.91552389 0.18838935 0.61732187 0.13022829]
 [0.58003899 0.45412995 0.18356513 0.43902468]
 [0.16100157 0.8709022  0.27592673 0.95539315]]

 6x6 Array with border 0 : 
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.53435733 0.90728663 0.84298865 0.17068102 0.        ]
 [0.         0.91552389 0.18838935 0.61732187 0.13022829 0.        ]
 [0.         0.58003899 0.45412995 0.18356513 0.43902468 0.        ]
 [0.         0.16100157 0.8709022  0.27592673 0.95539315 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

array1 = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5 : \n", array1)

Array of integers from 10 to 60 with a step of 5 : 
 [10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

array1  = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(array1)
lower_case = np.char.lower(array1)
title_case = np.char.title(array1)
capitalize_case = np.char.capitalize(array1)

print("Original Array:\n", array1)
print("\nUppercase:\n", upper_case)
print("\nLowercase:\n", lower_case)
print("\nTitle Case:\n", title_case)
print("\nCapitalize Case:\n", capitalize_case)

Original Array:
 ['python' 'numpy' 'pandas']

Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
 ['python' 'numpy' 'pandas']

Title Case:
 ['Python' 'Numpy' 'Pandas']

Capitalize Case:
 ['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

array1 = np.array(['hello', 'numpy', 'world'])

space_words = np.char.join(' ', array1)

print("Original Array:\n", array1)
print("\nArray with Spaces:\n", space_words)

Original Array:
 ['hello' 'numpy' 'world']

Array with Spaces:
 ['h e l l o' 'n u m p y' 'w o r l d']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1 : \n ", array1)
print("\n Array 2 : \n ", array2)

print("\n Addition:\n", addition)
print("\n Subtraction:\n", subtraction)
print("\n Multiplication:\n", multiplication)
print("\n Division:\n", division)

Array 1 : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Array 2 : 
  [[9 8 7]
 [6 5 4]
 [3 2 1]]

 Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

 Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

 Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

 Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

array1 = np.eye(5)

print("5x5 Identity Matrix : \n ", array1)

diagonal_element = np.diagonal(array1)

print("\n Diagonal elements : \n", diagonal_element)

5x5 Identity Matrix : 
  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 Diagonal elements : 
 [1. 1. 1. 1. 1.]


In [ ]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

array1 = np.random.randint(0, 1001, size = 100)

def prime_no(n):
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

numbers = [num for num in array1 if prime_no(num)]

print("Random Integers : \n", array1)
print("\n Prime Numbers in the Array : \n", numbers)

Random Integers : 
 [249 217 486 400 636 703 836 747 388 968 350 878 526 194 489 549 305 797
 217 354 353 210 779 845 610 827 550 633 583 241 205 225 753 103 498 259
  60 308  12 796 411 594 144 533 659 349 968 307 181 955 513 217 155 405
 121 137 919 678 224 901 831 849 340 949 253 717 132 585 498 368 187 793
 778 900  38 566 413 131 141 754 686 511 669 241 942 137 490 121 745 307
 551  78 718 493 655 300 572 636  89 108]

 Prime Numbers in the Array : 
 [797, 353, 827, 241, 103, 659, 349, 307, 181, 137, 919, 131, 241, 137, 307, 89]


In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

daily_temperature = np.random.uniform(0, 35, size = 30)

print("Daily Temperature for the month : \n", daily_temperature)

weekly_temperature =np.pad(daily_temperature, (0, 7 - (daily_temperature.size % 7)), constant_values=np.nan).reshape(-1, 7)

weekly_averages = np.nanmean(weekly_temperature, axis = 1)

print("\n Weekly Averages : \n", weekly_averages)

Daily Temperature for the month : 
 [30.72464584 10.89507551  0.58300454 18.28952438 12.21358335 22.25808681
 16.04311602  1.53555702 14.31262082 15.96219336 28.44015965 13.17569425
 24.82627109 20.79160763  2.76075728 13.72279931  5.8549556  10.99011094
  6.65544064 25.83694956  4.32422976 17.19253803  0.95463779 16.47068934
  0.85386251  7.87979578  9.71432943 30.45973895 19.00119059  2.08604179]

 Weekly Averages : 
 [15.85814806 17.00630055 10.02074901 11.9322274  10.54361619]
